# Generated by Django 4.0.4 on 2022-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Nutrition', models.CharField(max_length=256)),
                ('Allergy', models.CharField(max_length=20)),
                ('category', models.ManyToManyField(to='product.category')),
            ],
            options={
                'db_table': 'drink',
            },
        ),
    ]
